### PR TITLE
Switch to using xr.open_dataset to read nwp data

### LINKED ISSUE #3: Segmentation fault when reading BOM NWP data
We are getting segmentation faults on our doc builds when reading the BOM NWP data, see e.g.  here
https://readthedocs.org/projects/pysteps/builds/24750574/

I was able to reproduce it locally and to track it down to the `open_mfdataset` method in xarray:
```
>>> filename="/Users/daniele/pysteps-data/nwp/bom/2020/10/31/20201031_0000_regrid_short.nc"
>>> ds_rainfall = xr.open_mfdataset(
...         filename,
...         combine="nested",
...         concat_dim="time",
...         lock=False,
...         parallel=True,
...     )
>>> ds_rainfall.load()
python(29750,0x285013000) malloc: Region cookie corrupted for region 0x290000000 (value is 0)[0x290007ffc]
python(29750,0x285013000) malloc: *** set a breakpoint in malloc_error_break to debug
zsh: abort      python
```

Using the plain `xr.open_dataset` (which should be enough, since it's always a single netcdf file) avoids the error:
```
>>> import xarray as xr
>>> filename="/Users/daniele/pysteps-data/nwp/bom/2020/10/31/20201031_0000_regrid_short.nc"
>>> ds_rainfall = xr.open_dataset(
...         filename,
...     )
>>> 
>>> ds_rainfall
>>> ds_rainfall.load()
<xarray.Dataset> Size: 154MB
Dimensions:     (y: 512, time: 145, n2: 2, x: 512)
Coordinates:
  * y           (y) float64 4kB 127.8 127.2 126.8 126.2 ... -126.8 -127.2 -127.8
  * x           (x) float64 4kB -127.8 -127.2 -126.8 ... 126.8 127.2 127.8
  * time        (time) datetime64[ns] 1kB 2020-10-31 ... 2020-11-01
Dimensions without coordinates: n2
Data variables:
    y_bounds    (time, y, n2) float64 1MB 128.0 127.5 127.5 ... -127.5 -128.0
    x_bounds    (time, x, n2) float64 1MB -128.0 -127.5 -127.5 ... 127.5 128.0
    proj        int8 1B 32
    accum_prcp  (time, y, x) float32 152MB 0.0 0.0 0.0 ... 0.7031 0.8385 0.8385
Attributes:
    Conventions:   CF-1.5,ACDD-1.3
    source:        Regrided NWP rainfall forecast data
    date_created:  20201031
    summary:       Contains regrid NWP Rainfall forecast data
    title:         Rainfall forecast data
    base_date:     20201031
    base_time:     0
```

environment:
```
# Name                    Version                   Build  Channel
accessible-pygments       0.0.5                    pypi_0    pypi
alabaster                 0.7.16                   pypi_0    pypi
attrs                     23.2.0                   pypi_0    pypi
aws-c-auth                0.7.22               h27bc0eb_5    conda-forge
aws-c-cal                 0.6.15               h5db4892_0    conda-forge
aws-c-common              0.9.19               h99b78c6_0    conda-forge
aws-c-compression         0.2.18               h5db4892_6    conda-forge
aws-c-event-stream        0.4.2               h4de9e5c_13    conda-forge
aws-c-http                0.8.2                h2c662d3_2    conda-forge
aws-c-io                  0.14.9               h8709d7d_2    conda-forge
aws-c-mqtt                0.10.4               h5fc5ab5_6    conda-forge
aws-c-s3                  0.5.10               h48f01f6_3    conda-forge
aws-c-sdkutils            0.1.16               h5db4892_2    conda-forge
aws-checksums             0.1.18               h5db4892_6    conda-forge
aws-crt-cpp               0.26.12              h9d69022_0    conda-forge
aws-sdk-cpp               1.11.329             h6bd5272_5    conda-forge
babel                     2.15.0                   pypi_0    pypi
beautifulsoup4            4.12.3                   pypi_0    pypi
black                     24.4.2                   pypi_0    pypi
bokeh                     3.4.1              pyhd8ed1ab_0    conda-forge
brotli-python             1.1.0           py310h1253130_1    conda-forge
bzip2                     1.0.8                h93a5062_5    conda-forge
c-ares                    1.28.1               h93a5062_0    conda-forge
ca-certificates           2024.6.2             hf0a4a13_0    conda-forge
certifi                   2024.6.2                 pypi_0    pypi
cftime                    1.6.4                    pypi_0    pypi
charset-normalizer        3.3.2                    pypi_0    pypi
click                     8.1.7           unix_pyh707e725_0    conda-forge
cloudpickle               3.0.0              pyhd8ed1ab_0    conda-forge
contourpy                 1.2.1           py310h21239e6_0    conda-forge
coverage                  7.5.3                    pypi_0    pypi
cycler                    0.12.1                   pypi_0    pypi
cytoolz                   0.12.3          py310hd125d64_0    conda-forge
dask                      2024.6.1                 pypi_0    pypi
dask-core                 2024.6.0           pyhd8ed1ab_0    conda-forge
dask-expr                 1.1.3              pyhd8ed1ab_0    conda-forge
distributed               2024.6.0           pyhd8ed1ab_0    conda-forge
docutils                  0.21.2                   pypi_0    pypi
exceptiongroup            1.2.1                    pypi_0    pypi
fonttools                 4.53.0                   pypi_0    pypi
freetype                  2.12.1               hadb7bae_2    conda-forge
fsspec                    2024.6.0           pyhff2d567_0    conda-forge
gflags                    2.2.2             hc88da5d_1004    conda-forge
glog                      0.7.1                heb240a5_0    conda-forge
idna                      3.7                      pypi_0    pypi
imageio                   2.34.1                   pypi_0    pypi
imagesize                 1.4.1                    pypi_0    pypi
importlib-metadata        7.1.0              pyha770c72_0    conda-forge
importlib_metadata        7.1.0                hd8ed1ab_0    conda-forge
iniconfig                 2.0.0                    pypi_0    pypi
jinja2                    3.1.4              pyhd8ed1ab_0    conda-forge
jsmin                     3.0.1                    pypi_0    pypi
jsonschema                4.22.0                   pypi_0    pypi
jsonschema-specifications 2023.12.1                pypi_0    pypi
kiwisolver                1.4.5                    pypi_0    pypi
krb5                      1.21.2               h92f50d5_0    conda-forge
latexcodec                3.0.0                    pypi_0    pypi
lazy-loader               0.4                      pypi_0    pypi
lcms2                     2.16                 ha0e7c42_0    conda-forge
lerc                      4.0.0                h9a09cb3_0    conda-forge
libabseil                 20240116.2      cxx17_hebf3989_0    conda-forge
libarrow                  16.1.0           h431211a_9_cpu    conda-forge
libarrow-acero            16.1.0           h00cdb27_9_cpu    conda-forge
libarrow-dataset          16.1.0           h00cdb27_9_cpu    conda-forge
libarrow-substrait        16.1.0           hc68f6b8_9_cpu    conda-forge
libblas                   3.9.0           22_osxarm64_openblas    conda-forge
libbrotlicommon           1.1.0                hb547adb_1    conda-forge
libbrotlidec              1.1.0                hb547adb_1    conda-forge
libbrotlienc              1.1.0                hb547adb_1    conda-forge
libcblas                  3.9.0           22_osxarm64_openblas    conda-forge
libcrc32c                 1.1.2                hbdafb3b_0    conda-forge
libcurl                   8.8.0                h7b6f9a7_0    conda-forge
libcxx                    17.0.6               h5f092b4_0    conda-forge
libdeflate                1.20                 h93a5062_0    conda-forge
libedit                   3.1.20191231         hc8eb9b7_2    conda-forge
libev                     4.33                 h93a5062_2    conda-forge
libevent                  2.1.12               h2757513_1    conda-forge
libffi                    3.4.2                h3422bc3_5    conda-forge
libgfortran               5.0.0           13_2_0_hd922786_3    conda-forge
libgfortran5              13.2.0               hf226fd6_3    conda-forge
libgoogle-cloud           2.25.0               hfe08963_0    conda-forge
libgoogle-cloud-storage   2.25.0               h3fa5b87_0    conda-forge
libgrpc                   1.62.2               h9c18a4f_0    conda-forge
libjpeg-turbo             3.0.0                hb547adb_1    conda-forge
liblapack                 3.9.0           22_osxarm64_openblas    conda-forge
libnghttp2                1.58.0               ha4dd798_1    conda-forge
libopenblas               0.3.27          openmp_h6c19121_0    conda-forge
libparquet                16.1.0           hcf52c46_9_cpu    conda-forge
libpng                    1.6.43               h091b4b1_0    conda-forge
libprotobuf               4.25.3               hbfab5d5_0    conda-forge
libre2-11                 2023.09.01           h7b2c953_2    conda-forge
libsqlite                 3.46.0               hfb93653_0    conda-forge
libssh2                   1.11.0               h7a5bd25_0    conda-forge
libthrift                 0.19.0               h026a170_1    conda-forge
libtiff                   4.6.0                h07db509_3    conda-forge
libutf8proc               2.8.0                h1a8c8d9_0    conda-forge
libwebp-base              1.4.0                h93a5062_0    conda-forge
libxcb                    1.15                 hf346824_0    conda-forge
libzlib                   1.3.1                hfb2fe0b_1    conda-forge
llvm-openmp               18.1.7               hde57baf_0    conda-forge
locket                    1.0.0              pyhd8ed1ab_0    conda-forge
lz4                       4.3.3           py310haecba8d_0    conda-forge
lz4-c                     1.9.4                hb7217d7_0    conda-forge
markupsafe                2.1.5           py310hd125d64_0    conda-forge
matplotlib                3.9.0                    pypi_0    pypi
msgpack-python            1.0.8           py310he1a186f_0    conda-forge
mypy-extensions           1.0.0                    pypi_0    pypi
ncurses                   6.5                  hb89a1cb_0    conda-forge
netcdf4                   1.7.1                    pypi_0    pypi
networkx                  3.3                      pypi_0    pypi
numpy                     2.0.0           py310h52bbd9b_0    conda-forge
opencv-python             4.10.0.84                pypi_0    pypi
openjpeg                  2.5.2                h9f1df11_0    conda-forge
openssl                   3.3.1                hfb2fe0b_0    conda-forge
orc                       2.0.1                h47ade37_1    conda-forge
packaging                 24.1               pyhd8ed1ab_0    conda-forge
pandas                    2.2.2           py310h2216879_1    conda-forge
partd                     1.4.2              pyhd8ed1ab_0    conda-forge
pathspec                  0.12.1                   pypi_0    pypi
pillow                    10.3.0          py310h81a8c2e_0    conda-forge
pip                       24.0               pyhd8ed1ab_0    conda-forge
platformdirs              4.2.2                    pypi_0    pypi
pluggy                    1.5.0                    pypi_0    pypi
psutil                    5.9.8           py310hd125d64_0    conda-forge
pthread-stubs             0.4               h27ca646_1001    conda-forge
pyarrow                   16.1.0          py310h24597f5_3    conda-forge
pyarrow-core              16.1.0          py310h2e300fa_3_cpu    conda-forge
pyarrow-hotfix            0.6                pyhd8ed1ab_0    conda-forge
pybtex                    0.24.0                   pypi_0    pypi
pybtex-docutils           1.0.3                    pypi_0    pypi
pydata-sphinx-theme       0.15.3                   pypi_0    pypi
pygments                  2.18.0                   pypi_0    pypi
pyparsing                 3.1.2                    pypi_0    pypi
pyproj                    3.6.1                    pypi_0    pypi
pysocks                   1.7.1              pyha2e5f31_6    conda-forge
pysteps                   1.10.0                   pypi_0    pypi
pysteps-nwp-importers     0.1                       dev_0    <develop>
pytest                    8.2.2                    pypi_0    pypi
pytest-cov                5.0.0                    pypi_0    pypi
python                    3.10.14         h2469fbe_0_cpython    conda-forge
python-dateutil           2.9.0.post0              pypi_0    pypi
python-tzdata             2024.1             pyhd8ed1ab_0    conda-forge
python_abi                3.10                    4_cp310    conda-forge
pytz                      2024.1             pyhd8ed1ab_0    conda-forge
pyyaml                    6.0.1           py310h2aa6e3c_1    conda-forge
re2                       2023.09.01           h4cba328_2    conda-forge
readline                  8.2                  h92ec313_1    conda-forge
readthedocs-sphinx-ext    2.2.5                    pypi_0    pypi
referencing               0.35.1                   pypi_0    pypi
requests                  2.32.3                   pypi_0    pypi
rpds-py                   0.18.1                   pypi_0    pypi
scikit-image              0.24.0                   pypi_0    pypi
scipy                     1.13.1                   pypi_0    pypi
setuptools                70.1.0                   pypi_0    pypi
six                       1.16.0             pyh6c4a22f_0    conda-forge
snappy                    1.2.0                hd04f947_1    conda-forge
snowballstemmer           2.2.0                    pypi_0    pypi
sortedcontainers          2.4.0              pyhd8ed1ab_0    conda-forge
soupsieve                 2.5                      pypi_0    pypi
sphinx                    7.3.7                    pypi_0    pypi
sphinx-book-theme         1.1.3                    pypi_0    pypi
sphinx-gallery            0.16.0                   pypi_0    pypi
sphinxcontrib-applehelp   1.0.8                    pypi_0    pypi
sphinxcontrib-bibtex      2.6.2                    pypi_0    pypi
sphinxcontrib-devhelp     1.0.6                    pypi_0    pypi
sphinxcontrib-htmlhelp    2.0.5                    pypi_0    pypi
sphinxcontrib-jsmath      1.0.1                    pypi_0    pypi
sphinxcontrib-qthelp      1.0.7                    pypi_0    pypi
sphinxcontrib-serializinghtml 1.1.10                   pypi_0    pypi
tblib                     3.0.0              pyhd8ed1ab_0    conda-forge
tifffile                  2024.6.18                pypi_0    pypi
tk                        8.6.13               h5083fa2_1    conda-forge
tomli                     2.0.1                    pypi_0    pypi
toolz                     0.12.1             pyhd8ed1ab_0    conda-forge
tornado                   6.4.1           py310ha6dd24b_0    conda-forge
typing-extensions         4.12.2                   pypi_0    pypi
tzdata                    2024a                h0c530f3_0    conda-forge
urllib3                   2.2.2              pyhd8ed1ab_0    conda-forge
wheel                     0.43.0             pyhd8ed1ab_1    conda-forge
xarray                    2024.6.0                 pypi_0    pypi
xorg-libxau               1.0.11               hb547adb_0    conda-forge
xorg-libxdmcp             1.1.3                h27ca646_0    conda-forge
xyzservices               2024.6.0           pyhd8ed1ab_0    conda-forge
xz                        5.2.6                h57fd34a_0    conda-forge
yaml                      0.2.5                h3422bc3_2    conda-forge
zict                      3.0.0              pyhd8ed1ab_0    conda-forge
zipp                      3.19.2             pyhd8ed1ab_0    conda-forge
zstd                      1.5.6                hb46c0d2_0    conda-forge
```

FYI @RubenImhoff @ladc @cvelascof

### PR DESCRIPTION
**Pull request by dnerini**
closes #3

### CODE REVIEW

**Review by RubenImhoff — APPROVED** [review]
Hi @dnerini, 
Great work! This is indeed a typical problem with the `open_mfdataset` method. Your changes seem fine to me. If @cvelascof also approves, we're good to go, I'd say.

**Review by cvelascof — CHANGES_REQUESTED** [review]
HI @dnerini, thanks for tracking these bugs. 
I may prefer to replace `open_mfdataset` for `open_dataset` inside of `_import_bom_nwp_data_xr` and other similar functions in the other importers, rather than eliminate these functions. 
This may allow us to identify the real reason of the segmentation fault later on.

**Comment by dnerini** [comment]
hi @cvelascof , thanks for the feedback. I implemented your suggestion in [3b3c34f](https://github.com/pySTEPS/pysteps-nwp-importers/pull/4/commits/3b3c34f77959816ab146e394d028e2240f568140), I hope I got it right?

**Review by cvelascof — APPROVED** [review]
Awesome @dnerini ... all good with the new changes ... thanks

**Pull request merged**
